// Nigerian banks per NDIC categorisation
export const BANKS: string[] = [
  // Commercial
  "Access Bank Plc",
  "Alpha Morgan Bank Limited",
  "Citibank Nigeria Limited",
  "Ecobank Nigeria Limited",
  "Fidelity Bank Plc",
  "First Bank of Nigeria Limited",
  "First City Monument Bank Limited",
  "Globus Bank Limited",
  "Guaranty Trust Bank Limited",
  "Keystone Bank Limited",
  "Optimus Bank",
  "Parallex Bank Limited",
  "Polaris Bank Limited",
  "Premium Trust Bank",
  "Providus Bank Plc",
  "Signature Bank Limited",
  "Stanbic IBTC Bank Plc",
  "Standard Chartered Bank Limited",
  "Sterling Bank Plc",
  "SunTrust Bank Limited",
  "Tatum Bank Limited",
  "Titan Trust Bank Limited",
  "Union Bank Plc",
  "United Bank for Africa Plc",
  "Unity Bank Plc",
  "Wema Bank Plc",
  "Zenith Bank Plc",
  // Merchant
  "Coronation Merchant Bank Limited",
  "FBN Quest Merchant Bank Limited",
  "FSDH Merchant Bank Limited",
  "Greenwich Merchant Bank Limited",
  "Nova Merchant Bank Limited",
  "Rand Merchant Bank Limited",
  // Non-Interest
  "Jaiz Bank PLC",
  "Lotus Bank Ltd",
  "Summit Bank Limited",
  "Taj Bank",
  "The Alternative Bank",
  // Payment Service Banks
  "9 PSB",
  "Hope PSB",
  "Money Master PSB",
  "MOMO PSB",
  "SmartCash PSB",
  // Primary Mortgage Banks
  "Abbey Mortgage Bank Plc",
  "Platinum Mortgage Bank",
  "Mayfresh Mortgage Bank",
  "Jubilee-Life Mortgage Bank",
  "Aso Savings & Loans Plc",
  "Trust Bond Mortgage Bank",
  "SunTrust Mortgage Bank",
  "Infinity Trust Mortgage Bank Plc",
  "Haggai Mortgage Bank",
  "Imperial Mortgage Bank",
  "Nigeria Police Mortgage Bank",
  "FOKAS Savings & Loans",
  "Centage Savings & Loans",
  "Resort Savings & Loans",
  "Skyfield Savings and Loans",
  "FHA Homes Limited",
  "FBN Mortgages Ltd",
  "STB Building Society",
  "Omoluabi / Living Spring Savings & Loans",
  "First Generation Homes",
  "Global Trust Savings & Loans",
  "AG Homes Savings & Loans",
  "Kebbi State Homes S & L",
  "Mutual Alliance Savings & Loans",
  "Lagos Building and Invest. Co.",
  "Refuge Home S & L",
  "Safe Trust Savings & Loans",
  "Delta Mortgage Finance",
  "New Prudential Building Society",
  "Home-Base Mortgage",
  "Akwa Savings & Loans",
  "Gateway Savings & Loans",
  "United/Spring Mortgage",
  "Kogi State Savings & Loans",
  "Jigawa Savings & Loans",
  "City-Code Savings & Loans",
  "Taraba State Savings & Loans",
  "MGSL Mortgage Bank",
  "AHCOL Savings & Loans",
  "Coop Savings and Loans",
  "Accord Savings & Loans",
  "Adamawa Savings & Loans",
  "Trans-Atlantic Mortgages Limited",
  // Non-Bank Mobile Money Operators
  "Abeg Technologies Limited",
  "Cellulant Nigeria Ltd",
  "Chams Plc",
  "E-tranzact International Plc",
  "Funds and Electronic Transfer Solution",
  "Fortis Mobile Money Ltd",
  "Hendomark Nigeria Ltd",
  "KongaPay Technologies Limited",
  "Mkudi Mobile Money",
  "Now Now Digital Services Ltd",
  "Opay Digital Services Limited",
  "Pagatech Ltd",
  "Palmpay Ltd",
  "Parkway Project Ltd",
  "Teasy International Ltd",
  "Virtual Terminal Network Ltd",
  "Visual ICT Ltd",
  "Xpress Mts Limited",
];
