/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardMoneyRouteImport } from './routes/dashboard.money'
import { Route as ApiPublicHooksWeeklyDigestRouteImport } from './routes/api/public/hooks/weekly-digest'
import { Route as ApiPublicHooksRunUpkeepRouteImport } from './routes/api/public/hooks/run-upkeep'
import { Route as ApiPublicHooksFinalizeTerminationsRouteImport } from './routes/api/public/hooks/finalize-terminations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMoneyRoute = DashboardMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicHooksWeeklyDigestRoute =
  ApiPublicHooksWeeklyDigestRouteImport.update({
    id: '/api/public/hooks/weekly-digest',
    path: '/api/public/hooks/weekly-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunUpkeepRoute = ApiPublicHooksRunUpkeepRouteImport.update({
  id: '/api/public/hooks/run-upkeep',
  path: '/api/public/hooks/run-upkeep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFinalizeTerminationsRoute =
  ApiPublicHooksFinalizeTerminationsRouteImport.update({
    id: '/api/public/hooks/finalize-terminations',
    path: '/api/public/hooks/finalize-terminations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/dashboard/money': typeof DashboardMoneyRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dev/components': typeof DevComponentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/finalize-terminations': typeof ApiPublicHooksFinalizeTerminationsRoute
  '/api/public/hooks/run-upkeep': typeof ApiPublicHooksRunUpkeepRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/dashboard/money': typeof DashboardMoneyRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dev/components': typeof DevComponentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/hooks/finalize-terminations': typeof ApiPublicHooksFinalizeTerminationsRoute
  '/api/public/hooks/run-upkeep': typeof ApiPublicHooksRunUpkeepRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/dashboard/money': typeof DashboardMoneyRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dev/components': typeof DevComponentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/hooks/finalize-terminations': typeof ApiPublicHooksFinalizeTerminationsRoute
  '/api/public/hooks/run-upkeep': typeof ApiPublicHooksRunUpkeepRoute
  '/api/public/hooks/weekly-digest': typeof ApiPublicHooksWeeklyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/dashboard/money'
    | '/dashboard/team'
    | '/dev/components'
    | '/dashboard/'
    | '/api/public/hooks/finalize-terminations'
    | '/api/public/hooks/run-upkeep'
    | '/api/public/hooks/weekly-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/dashboard/money'
    | '/dashboard/team'
    | '/dev/components'
    | '/dashboard'
    | '/api/public/hooks/finalize-terminations'
    | '/api/public/hooks/run-upkeep'
    | '/api/public/hooks/weekly-digest'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/dashboard/money'
    | '/dashboard/team'
    | '/dev/components'
    | '/dashboard/'
    | '/api/public/hooks/finalize-terminations'
    | '/api/public/hooks/run-upkeep'
    | '/api/public/hooks/weekly-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  DevComponentsRoute: typeof DevComponentsRoute
  ApiPublicHooksFinalizeTerminationsRoute: typeof ApiPublicHooksFinalizeTerminationsRoute
  ApiPublicHooksRunUpkeepRoute: typeof ApiPublicHooksRunUpkeepRoute
  ApiPublicHooksWeeklyDigestRoute: typeof ApiPublicHooksWeeklyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/money': {
      id: '/dashboard/money'
      path: '/money'
      fullPath: '/dashboard/money'
      preLoaderRoute: typeof DashboardMoneyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/hooks/weekly-digest': {
      id: '/api/public/hooks/weekly-digest'
      path: '/api/public/hooks/weekly-digest'
      fullPath: '/api/public/hooks/weekly-digest'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-upkeep': {
      id: '/api/public/hooks/run-upkeep'
      path: '/api/public/hooks/run-upkeep'
      fullPath: '/api/public/hooks/run-upkeep'
      preLoaderRoute: typeof ApiPublicHooksRunUpkeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/finalize-terminations': {
      id: '/api/public/hooks/finalize-terminations'
      path: '/api/public/hooks/finalize-terminations'
      fullPath: '/api/public/hooks/finalize-terminations'
      preLoaderRoute: typeof ApiPublicHooksFinalizeTerminationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardMoneyRoute: typeof DashboardMoneyRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMoneyRoute: DashboardMoneyRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  DevComponentsRoute: DevComponentsRoute,
  ApiPublicHooksFinalizeTerminationsRoute:
    ApiPublicHooksFinalizeTerminationsRoute,
  ApiPublicHooksRunUpkeepRoute: ApiPublicHooksRunUpkeepRoute,
  ApiPublicHooksWeeklyDigestRoute: ApiPublicHooksWeeklyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
